import type { AppEntry } from "@/types";

export const PLATFORM_META = {
  lovable: { label: "Lovable", color: "bg-pink-500", icon: "💖" },
  bolt: { label: "Bolt", color: "bg-yellow-500", icon: "⚡" },
  replit: { label: "Replit", color: "bg-orange-500", icon: "🔁" },
  v0: { label: "v0", color: "bg-black", icon: "▲" },
  cursor: { label: "Cursor", color: "bg-blue-600", icon: "⬡" },
  windsurf: { label: "Windsurf", color: "bg-cyan-500", icon: "🏄" },
} as const;

export const ALL_TAGS = [
  "dashboard", "productivity", "game", "ai", "finance",
  "social", "tool", "form", "landing page", "e-commerce",
  "portfolio", "chat", "analytics", "calendar",
];

export const MOCK_APPS: AppEntry[] = [
  {
    id: "habit-tracker-ai",
    title: "AI Habit Tracker",
    description: "Streak-based habit tracker with AI-generated motivational nudges and weekly summaries.",
    longDescription: "A clean habit tracking app that uses AI to personalize your motivation. Set habits, check them off daily, and get weekly AI-written summaries of your progress. Includes streak visualization and smart reminders.",
    creator: "makerdan",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=makerdan",
    tags: ["productivity", "ai", "tool"],
    previewUrl: "",
    screenshotUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80",
    forkUrls: {
      lovable: "https://lovable.dev",
      bolt: "https://bolt.new",
      replit: "https://replit.com",
    },
    likes: 847,
    forks: 213,
    views: 4201,
    createdAt: "2025-05-10",
    updatedAt: "2025-06-01",
    featured: true,
  },
  {
    id: "budget-viz",
    title: "Budget Visualizer",
    description: "Upload a CSV of transactions and get instant AI-categorized spending breakdowns with charts.",
    longDescription: "Drop in your bank export CSV and get a beautiful breakdown of where your money goes. The AI categorizes spending automatically and flags unusual patterns. No sign-up required — fully local processing.",
    creator: "financevibes",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    tags: ["finance", "dashboard", "ai"],
    screenshotUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    forkUrls: {
      lovable: "https://lovable.dev",
      v0: "https://v0.dev",
    },
    likes: 1204,
    forks: 389,
    views: 8932,
    createdAt: "2025-04-22",
    updatedAt: "2025-05-30",
    featured: true,
    isPro: false,
  },
  {
    id: "kanban-minimal",
    title: "Minimal Kanban",
    description: "Dead-simple kanban board — drag, drop, done. No accounts, no friction.",
    creator: "zenwebb",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=zenwebb",
    tags: ["productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
    forkUrls: {
      bolt: "https://bolt.new",
      lovable: "https://lovable.dev",
      replit: "https://replit.com",
      v0: "https://v0.dev",
    },
    likes: 632,
    forks: 508,
    views: 6123,
    createdAt: "2025-03-15",
    updatedAt: "2025-06-10",
  },
  {
    id: "ai-quiz-gen",
    title: "AI Quiz Generator",
    description: "Paste any text or URL, generate a quiz instantly. Great for studying or testing others.",
    creator: "quizcrafters",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=quizcrafters",
    tags: ["ai", "tool", "productivity"],
    screenshotUrl: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800&q=80",
    forkUrls: {
      lovable: "https://lovable.dev",
      replit: "https://replit.com",
    },
    likes: 443,
    forks: 187,
    views: 3290,
    createdAt: "2025-05-28",
    updatedAt: "2025-06-15",
  },
  {
    id: "saas-landing",
    title: "SaaS Landing Page Kit",
    description: "Clean, conversion-optimized landing page with hero, features, pricing, and FAQ. Fork and ship.",
    creator: "pixellaunch",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    tags: ["landing page", "e-commerce"],
    screenshotUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    forkUrls: {
      v0: "https://v0.dev",
      lovable: "https://lovable.dev",
      bolt: "https://bolt.new",
    },
    likes: 1891,
    forks: 1204,
    views: 18420,
    createdAt: "2025-02-10",
    updatedAt: "2025-06-01",
    featured: true,
    isPro: true,
  },
  {
    id: "wordle-clone",
    title: "Custom Wordle",
    description: "Wordle clone where you set your own word list. Run themed Wordle games for your community.",
    creator: "gamebuilder99",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=gamebuilder99",
    tags: ["game", "social", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1610374792793-f016b77ca51a?w=800&q=80",
    forkUrls: {
      replit: "https://replit.com",
      bolt: "https://bolt.new",
    },
    likes: 728,
    forks: 341,
    views: 5612,
    createdAt: "2025-04-01",
    updatedAt: "2025-04-20",
  },
  {
    id: "ai-cover-letter",
    title: "Cover Letter Writer",
    description: "Paste a job description + your resume summary, get a tailored cover letter in seconds.",
    creator: "jobhunthelper",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=jobhunthelper",
    tags: ["ai", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    forkUrls: {
      lovable: "https://lovable.dev",
      bolt: "https://bolt.new",
      v0: "https://v0.dev",
      cursor: "https://cursor.sh",
    },
    likes: 1103,
    forks: 467,
    views: 9840,
    createdAt: "2025-05-05",
    updatedAt: "2025-06-18",
  },
  {
    id: "portfolio-gen",
    title: "Dev Portfolio Generator",
    description: "GitHub-connected portfolio that auto-fills projects from your starred and contributed repos.",
    creator: "devshowcase",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=devshowcase",
    tags: ["portfolio", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80",
    forkUrls: {
      replit: "https://replit.com",
      lovable: "https://lovable.dev",
    },
    likes: 567,
    forks: 230,
    views: 4102,
    createdAt: "2025-05-18",
    updatedAt: "2025-06-05",
  },
];
