import type { AppEntry, CreatorProfile, ActivityEvent } from "@/types";

export const PLATFORM_META = {
  lovable: { label: "Lovable", color: "bg-pink-500", icon: "💖" },
  bolt: { label: "Bolt", color: "bg-yellow-500", icon: "⚡" },
  replit: { label: "Replit", color: "bg-orange-500", icon: "🔁" },
  v0: { label: "v0", color: "bg-black", icon: "▲" },
  cursor: { label: "Cursor", color: "bg-blue-600", icon: "⬡" },
  windsurf: { label: "Windsurf", color: "bg-cyan-500", icon: "🏄" },
} as const;

export const ALL_TAGS = [
  "dashboard", "productivity", "game", "ai", "finance",
  "social", "tool", "form", "landing page", "e-commerce",
  "portfolio", "chat", "analytics", "calendar", "music",
  "art", "writing", "health", "education", "utility",
];

// ─── Creators ────────────────────────────────────────────────────────────────

export const CREATORS: CreatorProfile[] = [
  {
    handle: "makerdan",
    displayName: "Dan Kowalski",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=makerdan",
    bio: "Building small tools that make daily life less annoying. Ex-designer, now full-time vibe coder.",
    location: "Austin, TX",
    twitter: "makerdan",
    appCount: 7,
    totalForks: 1840,
    totalLikes: 3200,
    isFoundingCreator: true,
    joinedAt: "2025-01-15",
    tags: ["productivity", "ai", "tool"],
  },
  {
    handle: "financevibes",
    displayName: "Priya Nair",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    bio: "Personal finance nerd who got tired of spreadsheets. Building better money tools for the rest of us.",
    location: "London, UK",
    twitter: "financevibes",
    appCount: 4,
    totalForks: 2103,
    totalLikes: 4800,
    isFoundingCreator: true,
    joinedAt: "2025-02-01",
    tags: ["finance", "dashboard", "analytics"],
  },
  {
    handle: "zenwebb",
    displayName: "Alex Webb",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=zenwebb",
    bio: "Minimalism enthusiast. I build apps that do one thing well. No bloat, no upsells.",
    location: "Portland, OR",
    appCount: 9,
    totalForks: 3201,
    totalLikes: 5100,
    isFoundingCreator: true,
    joinedAt: "2025-01-20",
    tags: ["productivity", "tool", "utility"],
  },
  {
    handle: "pixellaunch",
    displayName: "Camille Fontaine",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    bio: "UX designer who ships. I build landing pages and marketing tools that convert.",
    location: "Paris, France",
    twitter: "pixellaunch",
    appCount: 12,
    totalForks: 6820,
    totalLikes: 9400,
    isFoundingCreator: true,
    joinedAt: "2025-01-10",
    tags: ["landing page", "e-commerce", "tool"],
  },
  {
    handle: "gamebuilder99",
    displayName: "Sam Torres",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=gamebuilder99",
    bio: "Lifelong gamer building the casual games I always wanted. No engine, pure vibes.",
    location: "São Paulo, Brazil",
    appCount: 11,
    totalForks: 2950,
    totalLikes: 4200,
    isFoundingCreator: true,
    joinedAt: "2025-02-14",
    tags: ["game", "social", "tool"],
  },
  {
    handle: "quizcrafters",
    displayName: "Jo Mercer",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=quizcrafters",
    bio: "Teacher turned builder. Making learning tools that don't suck.",
    location: "Edinburgh, Scotland",
    appCount: 5,
    totalForks: 1102,
    totalLikes: 2100,
    isFoundingCreator: true,
    joinedAt: "2025-03-01",
    tags: ["ai", "tool", "education"],
  },
  {
    handle: "jobhunthelper",
    displayName: "Reina Park",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=jobhunthelper",
    bio: "Was laid off, built my way out of it. Now making job search tools so others can too.",
    location: "Seoul, South Korea",
    twitter: "jobhunthelper",
    appCount: 6,
    totalForks: 2840,
    totalLikes: 4700,
    isFoundingCreator: false,
    joinedAt: "2025-04-01",
    tags: ["ai", "productivity", "tool"],
  },
  {
    handle: "devshowcase",
    displayName: "Mateo Cruz",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=devshowcase",
    bio: "Full-stack dev learning to build for non-devs. Portfolio tools are my specialty.",
    location: "Buenos Aires, Argentina",
    appCount: 4,
    totalForks: 980,
    totalLikes: 1600,
    isFoundingCreator: false,
    joinedAt: "2025-04-15",
    tags: ["portfolio", "tool"],
  },
  {
    handle: "rhythmforge",
    displayName: "Talia Voss",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=rhythmforge",
    bio: "Music producer building tools I wish existed. Synths, sequencers, and sound experiments.",
    location: "Berlin, Germany",
    twitter: "rhythmforge",
    appCount: 8,
    totalForks: 3100,
    totalLikes: 5800,
    isFoundingCreator: true,
    joinedAt: "2025-02-20",
    tags: ["music", "art", "tool"],
  },
  {
    handle: "inkandpixel",
    displayName: "Yuki Tanaka",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    bio: "Illustrator who discovered vibe coding. Building tools for visual artists and storytellers.",
    location: "Tokyo, Japan",
    twitter: "inkandpixel",
    appCount: 6,
    totalForks: 2400,
    totalLikes: 4300,
    isFoundingCreator: true,
    joinedAt: "2025-03-05",
    tags: ["art", "tool", "writing"],
  },
  {
    handle: "healthhacker",
    displayName: "Nora Lindqvist",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=healthhacker",
    bio: "Nurse by day, health app builder by night. Practical tools that actually fit real workflows.",
    location: "Stockholm, Sweden",
    appCount: 5,
    totalForks: 1700,
    totalLikes: 2900,
    isFoundingCreator: false,
    joinedAt: "2025-04-20",
    tags: ["health", "utility", "tool"],
  },
  {
    handle: "chatlab",
    displayName: "Omar Hassan",
    avatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=chatlab",
    bio: "AI researcher who builds conversational tools for non-technical people. Accessibility-first.",
    location: "Cairo, Egypt",
    twitter: "chatlab",
    appCount: 7,
    totalForks: 3800,
    totalLikes: 6100,
    isFoundingCreator: true,
    joinedAt: "2025-01-28",
    tags: ["ai", "chat", "tool"],
  },
];

// ─── Apps ─────────────────────────────────────────────────────────────────────

export const MOCK_APPS: AppEntry[] = [
  {
    id: "habit-tracker-ai",
    title: "AI Habit Tracker",
    description: "Streak-based habit tracker with AI-generated motivational nudges and weekly summaries.",
    longDescription: "A clean habit tracking app that uses AI to personalize your motivation. Set habits, check them off daily, and get weekly AI-written summaries of your progress. Includes streak visualization and smart reminders.",
    creator: "makerdan",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=makerdan",
    tags: ["productivity", "ai", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new", replit: "https://replit.com" },
    likes: 847, forks: 213, views: 4201,
    createdAt: "2025-05-10", updatedAt: "2025-06-01", featured: true,
  },
  {
    id: "budget-viz",
    title: "Budget Visualizer",
    description: "Upload a CSV of transactions and get instant AI-categorized spending breakdowns with charts.",
    longDescription: "Drop in your bank export CSV and get a beautiful breakdown of where your money goes. The AI categorizes spending automatically and flags unusual patterns. No sign-up required — fully local processing.",
    creator: "financevibes",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    tags: ["finance", "dashboard", "ai"],
    screenshotUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", v0: "https://v0.dev" },
    likes: 1204, forks: 389, views: 8932,
    createdAt: "2025-04-22", updatedAt: "2025-05-30", featured: true,
  },
  {
    id: "kanban-minimal",
    title: "Minimal Kanban",
    description: "Dead-simple kanban board — drag, drop, done. No accounts, no friction.",
    creator: "zenwebb",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=zenwebb",
    tags: ["productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", lovable: "https://lovable.dev", replit: "https://replit.com", v0: "https://v0.dev" },
    likes: 632, forks: 508, views: 6123,
    createdAt: "2025-03-15", updatedAt: "2025-06-10",
  },
  {
    id: "ai-quiz-gen",
    title: "AI Quiz Generator",
    description: "Paste any text or URL, generate a quiz instantly. Great for studying or testing others.",
    creator: "quizcrafters",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=quizcrafters",
    tags: ["ai", "tool", "education"],
    screenshotUrl: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", replit: "https://replit.com" },
    likes: 443, forks: 187, views: 3290,
    createdAt: "2025-05-28", updatedAt: "2025-06-15",
  },
  {
    id: "saas-landing",
    title: "SaaS Landing Page Kit",
    description: "Conversion-optimized landing page with hero, features, pricing, and FAQ. Fork and ship in a day.",
    longDescription: "The landing page template I wish I had when launching my first product. Includes hero section with video support, feature grid, pricing table with annual/monthly toggle, FAQ accordion, and email capture. Fully responsive.",
    creator: "pixellaunch",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    tags: ["landing page", "e-commerce"],
    screenshotUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 1891, forks: 1204, views: 18420,
    createdAt: "2025-02-10", updatedAt: "2025-06-01", featured: true, isPro: true,
  },
  {
    id: "wordle-clone",
    title: "Custom Wordle",
    description: "Wordle clone where you set your own word list. Run themed Wordle games for your community.",
    creator: "gamebuilder99",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=gamebuilder99",
    tags: ["game", "social", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1610374792793-f016b77ca51a?w=800&q=80",
    forkUrls: { replit: "https://replit.com", bolt: "https://bolt.new" },
    likes: 728, forks: 341, views: 5612,
    createdAt: "2025-04-01", updatedAt: "2025-04-20",
  },
  {
    id: "ai-cover-letter",
    title: "Cover Letter Writer",
    description: "Paste a job description + your resume summary, get a tailored cover letter in seconds.",
    creator: "jobhunthelper",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=jobhunthelper",
    tags: ["ai", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new", v0: "https://v0.dev", cursor: "https://cursor.sh" },
    likes: 1103, forks: 467, views: 9840,
    createdAt: "2025-05-05", updatedAt: "2025-06-18",
  },
  {
    id: "portfolio-gen",
    title: "Dev Portfolio Generator",
    description: "GitHub-connected portfolio that auto-fills projects from your starred and contributed repos.",
    creator: "devshowcase",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=devshowcase",
    tags: ["portfolio", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80",
    forkUrls: { replit: "https://replit.com", lovable: "https://lovable.dev" },
    likes: 567, forks: 230, views: 4102,
    createdAt: "2025-05-18", updatedAt: "2025-06-05",
  },
  {
    id: "beat-sequencer",
    title: "Browser Beat Sequencer",
    description: "16-step drum machine that runs entirely in the browser. Export to WAV, share a link to your pattern.",
    longDescription: "No DAW, no plugins. A 16-step sequencer with 8 drum tracks, adjustable tempo, swing, and a sharable pattern URL. Export your beat as WAV. Built for musicians who want to sketch ideas fast on any device.",
    creator: "rhythmforge",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=rhythmforge",
    tags: ["music", "tool", "art"],
    screenshotUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    forkUrls: { replit: "https://replit.com", bolt: "https://bolt.new", cursor: "https://cursor.sh" },
    likes: 1340, forks: 612, views: 11200,
    createdAt: "2025-03-20", updatedAt: "2025-06-10", featured: true,
  },
  {
    id: "chord-finder",
    title: "Chord & Scale Explorer",
    description: "Click any note on a piano roll, see every chord and scale it belongs to. Great for producers and songwriters.",
    creator: "rhythmforge",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=rhythmforge",
    tags: ["music", "tool", "education"],
    screenshotUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", v0: "https://v0.dev" },
    likes: 892, forks: 310, views: 7800,
    createdAt: "2025-04-10", updatedAt: "2025-05-22",
  },
  {
    id: "mood-palette",
    title: "Mood Color Palette Generator",
    description: "Describe a feeling or scene in words, get an AI-generated color palette with hex codes ready to copy.",
    longDescription: "Type 'rainy afternoon in a Tokyo convenience store' and get 5 perfectly matched colors with names, hex codes, and a preview. Great for designers, artists, and anyone who thinks in color. Export to CSS, Figma, or PNG.",
    creator: "inkandpixel",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    tags: ["art", "tool", "ai"],
    screenshotUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", v0: "https://v0.dev", bolt: "https://bolt.new" },
    likes: 2104, forks: 890, views: 19300,
    createdAt: "2025-03-01", updatedAt: "2025-06-20", featured: true,
  },
  {
    id: "story-outline",
    title: "Story Outline Builder",
    description: "Visual 3-act structure tool for writers. Drag scenes between acts, see your story shape at a glance.",
    creator: "inkandpixel",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    tags: ["writing", "tool", "productivity"],
    screenshotUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", cursor: "https://cursor.sh" },
    likes: 671, forks: 245, views: 5400,
    createdAt: "2025-05-01", updatedAt: "2025-05-30",
  },
  {
    id: "symptom-log",
    title: "Symptom & Medication Log",
    description: "Private, local-first log for tracking symptoms, meds, and patterns over time. No account, no cloud.",
    creator: "healthhacker",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=healthhacker",
    tags: ["health", "utility", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", replit: "https://replit.com" },
    likes: 533, forks: 198, views: 4600,
    createdAt: "2025-05-12", updatedAt: "2025-06-02",
  },
  {
    id: "ai-chat-persona",
    title: "Custom AI Chat Persona",
    description: "Build a chatbot with a custom personality, knowledge base, and tone. Share via link.",
    longDescription: "Define a persona (name, role, style), give it a knowledge base (paste text or URL), and get a shareable chat link. Great for building support bots, educational assistants, or just a fun character. No backend required — runs on your API key.",
    creator: "chatlab",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=chatlab",
    tags: ["ai", "chat", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new", replit: "https://replit.com", cursor: "https://cursor.sh" },
    likes: 1780, forks: 830, views: 15600,
    createdAt: "2025-03-10", updatedAt: "2025-06-15", featured: true,
  },
  {
    id: "flashcard-ai",
    title: "AI Flashcard Maker",
    description: "Paste study material, get flashcards instantly. Spaced repetition built in.",
    creator: "quizcrafters",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=quizcrafters",
    tags: ["ai", "education", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 910, forks: 378, views: 8200,
    createdAt: "2025-04-15", updatedAt: "2025-06-01",
  },
  {
    id: "invoice-generator",
    title: "Freelancer Invoice Generator",
    description: "Fill in client details, line items, and tax rate. Download a clean PDF invoice in 30 seconds.",
    creator: "financevibes",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    tags: ["finance", "tool", "utility"],
    screenshotUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", bolt: "https://bolt.new", lovable: "https://lovable.dev" },
    likes: 1456, forks: 724, views: 13200,
    createdAt: "2025-02-25", updatedAt: "2025-05-10",
  },
  {
    id: "pomodoro-tracker",
    title: "Focus Pomodoro Timer",
    description: "Pomodoro timer with session history, custom intervals, and ambient sound picker.",
    creator: "makerdan",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=makerdan",
    tags: ["productivity", "tool", "utility"],
    screenshotUrl: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", replit: "https://replit.com", v0: "https://v0.dev" },
    likes: 788, forks: 302, views: 6900,
    createdAt: "2025-04-05", updatedAt: "2025-05-25",
  },
  {
    id: "color-contrast-checker",
    title: "Accessibility Color Checker",
    description: "Check any color pair for WCAG contrast compliance. Suggests fixes that keep your brand palette.",
    creator: "inkandpixel",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    tags: ["art", "tool", "utility"],
    screenshotUrl: "https://images.unsplash.com/photo-1579547621706-1a9c79d5c9f1?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", bolt: "https://bolt.new" },
    likes: 623, forks: 281, views: 5800,
    createdAt: "2025-04-28", updatedAt: "2025-05-20",
  },
  {
    id: "trivia-night",
    title: "Trivia Night Host",
    description: "Host live pub trivia from your phone. Players join via QR code, scores update in real time.",
    creator: "gamebuilder99",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=gamebuilder99",
    tags: ["game", "social", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    forkUrls: { replit: "https://replit.com", lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 1092, forks: 488, views: 10400,
    createdAt: "2025-03-28", updatedAt: "2025-06-08",
  },
  {
    id: "resume-optimizer",
    title: "ATS Resume Optimizer",
    description: "Paste your resume and a job description. Get a keyword gap analysis and suggested edits.",
    creator: "jobhunthelper",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=jobhunthelper",
    tags: ["ai", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", cursor: "https://cursor.sh", bolt: "https://bolt.new" },
    likes: 1320, forks: 593, views: 12100,
    createdAt: "2025-04-18", updatedAt: "2025-06-12",
  },
  {
    id: "calorie-tracker",
    title: "Simple Calorie Counter",
    description: "No barcode scanner needed. Search food, log portions, see your day at a glance. Clean and fast.",
    creator: "healthhacker",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=healthhacker",
    tags: ["health", "utility", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", replit: "https://replit.com" },
    likes: 445, forks: 162, views: 3900,
    createdAt: "2025-05-22", updatedAt: "2025-06-10",
  },
  {
    id: "daily-journal-ai",
    title: "AI Daily Journal",
    description: "Guided journaling with AI-generated prompts based on your mood. Weekly reflection summaries.",
    creator: "makerdan",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=makerdan",
    tags: ["ai", "writing", "productivity"],
    screenshotUrl: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 690, forks: 258, views: 5100,
    createdAt: "2025-05-30", updatedAt: "2025-06-18",
  },
  {
    id: "meeting-notes-ai",
    title: "Meeting Notes Summarizer",
    description: "Paste transcript or upload audio. Get action items, decisions, and a clean summary in seconds.",
    creator: "chatlab",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=chatlab",
    tags: ["ai", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", cursor: "https://cursor.sh", lovable: "https://lovable.dev" },
    likes: 1580, forks: 702, views: 14300,
    createdAt: "2025-03-15", updatedAt: "2025-06-05",
  },
  {
    id: "social-post-scheduler",
    title: "Social Media Post Planner",
    description: "Plan a week of posts in one view. Write captions, attach images, export a CSV for Buffer or Hootsuite.",
    creator: "pixellaunch",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    tags: ["social", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", v0: "https://v0.dev", bolt: "https://bolt.new" },
    likes: 834, forks: 367, views: 7600,
    createdAt: "2025-04-25", updatedAt: "2025-06-01",
  },
  {
    id: "link-in-bio",
    title: "Link-in-Bio Builder",
    description: "Custom link page for creators. Themes, analytics, and a drag-and-drop editor. Free alternative to Linktree.",
    creator: "pixellaunch",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    tags: ["social", "landing page", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", lovable: "https://lovable.dev", bolt: "https://bolt.new", replit: "https://replit.com" },
    likes: 2340, forks: 1450, views: 22800,
    createdAt: "2025-02-05", updatedAt: "2025-06-20", featured: true, isPro: true,
  },
  {
    id: "rpg-character-gen",
    title: "RPG Character Generator",
    description: "Roll stats, pick a class, generate a full character sheet with backstory written by AI.",
    creator: "gamebuilder99",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=gamebuilder99",
    tags: ["game", "ai", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1553481187-be93c21490a9?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", replit: "https://replit.com" },
    likes: 960, forks: 420, views: 8900,
    createdAt: "2025-04-08", updatedAt: "2025-05-15",
  },
  {
    id: "crypto-dashboard",
    title: "Personal Crypto Dashboard",
    description: "Track your portfolio across wallets without connecting them. Manual entry, beautiful charts.",
    creator: "financevibes",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    tags: ["finance", "dashboard", "analytics"],
    screenshotUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 1102, forks: 489, views: 9700,
    createdAt: "2025-03-25", updatedAt: "2025-06-14",
  },
  {
    id: "font-pairing",
    title: "Font Pairing Tool",
    description: "Browse Google Fonts combinations with live preview. Copy CSS in one click.",
    creator: "inkandpixel",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    tags: ["art", "tool", "utility"],
    screenshotUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", bolt: "https://bolt.new" },
    likes: 780, forks: 334, views: 7200,
    createdAt: "2025-04-20", updatedAt: "2025-05-28",
  },
  {
    id: "waitlist-page",
    title: "Waitlist Landing Page",
    description: "One-page waitlist with email capture, referral counter, and a social share nudge. Launch-ready.",
    creator: "pixellaunch",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixellaunch",
    tags: ["landing page", "tool", "social"],
    screenshotUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    forkUrls: { v0: "https://v0.dev", lovable: "https://lovable.dev", bolt: "https://bolt.new" },
    likes: 1670, forks: 980, views: 16400,
    createdAt: "2025-02-18", updatedAt: "2025-06-15", isPro: true,
  },
  {
    id: "writing-sprint-timer",
    title: "Writing Sprint Timer",
    description: "Distraction-free writing timer with word count, sprints, and a 'no delete' mode for flow state.",
    creator: "inkandpixel",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=inkandpixel",
    tags: ["writing", "productivity", "tool"],
    screenshotUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    forkUrls: { bolt: "https://bolt.new", replit: "https://replit.com" },
    likes: 492, forks: 178, views: 4200,
    createdAt: "2025-05-25", updatedAt: "2025-06-12",
  },
  {
    id: "ai-email-rewriter",
    title: "AI Email Tone Rewriter",
    description: "Paste a draft email, pick a tone (friendly, formal, assertive), get an instant rewrite.",
    creator: "chatlab",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=chatlab",
    tags: ["ai", "productivity", "writing"],
    screenshotUrl: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", bolt: "https://bolt.new", cursor: "https://cursor.sh" },
    likes: 1230, forks: 541, views: 11800,
    createdAt: "2025-03-30", updatedAt: "2025-06-10",
  },
  {
    id: "net-worth-tracker",
    title: "Net Worth Tracker",
    description: "Monthly net worth snapshot tool. Track assets and liabilities over time with a timeline chart.",
    creator: "financevibes",
    creatorAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=financevibes",
    tags: ["finance", "dashboard", "analytics"],
    screenshotUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    forkUrls: { lovable: "https://lovable.dev", v0: "https://v0.dev" },
    likes: 880, forks: 312, views: 7400,
    createdAt: "2025-04-30", updatedAt: "2025-06-02",
  },
];

// ─── Activity Feed ────────────────────────────────────────────────────────────

export const ACTIVITY_FEED: ActivityEvent[] = [
  { id: "a1", type: "fork", user: "creatorlabs", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=creatorlabs", appId: "mood-palette", appTitle: "Mood Color Palette Generator", platform: "lovable", timestamp: "just now" },
  { id: "a2", type: "submit", user: "rhythmforge", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=rhythmforge", appId: "chord-finder", appTitle: "Chord & Scale Explorer", timestamp: "2m ago" },
  { id: "a3", type: "fork", user: "designsprint", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=designsprint", appId: "saas-landing", appTitle: "SaaS Landing Page Kit", platform: "bolt", timestamp: "5m ago" },
  { id: "a4", type: "like", user: "indie_emma", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=indie_emma", appId: "beat-sequencer", appTitle: "Browser Beat Sequencer", timestamp: "8m ago" },
  { id: "a5", type: "fork", user: "vibedev_ro", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=vibedev_ro", appId: "ai-chat-persona", appTitle: "Custom AI Chat Persona", platform: "replit", timestamp: "12m ago" },
  { id: "a6", type: "fork", user: "pixelsmith", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=pixelsmith", appId: "link-in-bio", appTitle: "Link-in-Bio Builder", platform: "v0", timestamp: "15m ago" },
  { id: "a7", type: "submit", user: "healthhacker", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=healthhacker", appId: "calorie-tracker", appTitle: "Simple Calorie Counter", timestamp: "22m ago" },
  { id: "a8", type: "fork", user: "nocodejess", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=nocodejess", appId: "invoice-generator", appTitle: "Freelancer Invoice Generator", platform: "lovable", timestamp: "31m ago" },
  { id: "a9", type: "like", user: "buildermark", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=buildermark", appId: "trivia-night", appTitle: "Trivia Night Host", timestamp: "38m ago" },
  { id: "a10", type: "fork", user: "songstress_k", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=songstress_k", appId: "chord-finder", appTitle: "Chord & Scale Explorer", platform: "bolt", timestamp: "44m ago" },
  { id: "a11", type: "fork", user: "startupflo", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=startupflo", appId: "waitlist-page", appTitle: "Waitlist Landing Page", platform: "lovable", timestamp: "1h ago" },
  { id: "a12", type: "submit", user: "chatlab", userAvatar: "https://api.dicebear.com/7.x/adventurer/svg?seed=chatlab", appId: "ai-email-rewriter", appTitle: "AI Email Tone Rewriter", timestamp: "1h ago" },
];
